version: '3.4'

services:
  mymicroservice:
    environment:
      - ASPNETCORE_ENVIRONMENT
      - APPINSIGHTS_INSTRUMENTATIONKEY
      - AppConfig__Endpoint
      - FeatureManagement__RedisCache=True
    ports:
      - "9401:80" # Exposes port 80 from container as port 9400 on local machine
      
  mymicroservice.web:
    environment:
      - ASPNETCORE_ENVIRONMENT
      - APPINSIGHTS_INSTRUMENTATIONKEY
    ports:
      - "9400:80"

  seq:
    ports:
      - "9402:80"
  
  zipkin:
    ports:
      - "9403:9411"

  healthcheckui:
    environment:
      - ASPNETCORE_ENVIRONMENT
      - APPINSIGHTS_INSTRUMENTATIONKEY
    ports:
      - "9404:80"